language: python

python:
  - 3.6.2

install:
    - pip install -r requirements.txt

env:
  - DB_NAME=travis_ci_test

before_script:
    - psql -c "create database ${DB_NAME};" -U postgres

script:
    - python manage.py migrate
    - python manage.py test
